/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BienvenueRouteImport } from './routes/bienvenue'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ExercicesRouteImport } from './routes/exercices'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as ProgressionRouteImport } from './routes/progression'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as SeancesRouteImport } from './routes/seances'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueRoute = BienvenueRouteImport.update({
  id: '/bienvenue',
  path: '/bienvenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicesRoute = ExercicesRouteImport.update({
  id: '/exercices',
  path: '/exercices',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressionRoute = ProgressionRouteImport.update({
  id: '/progression',
  path: '/progression',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const SeancesRoute = SeancesRouteImport.update({
  id: '/seances',
  path: '/seances',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/exercices': typeof ExercicesRoute
  '/planning': typeof PlanningRoute
  '/progression': typeof ProgressionRoute
  '/reglages': typeof ReglagesRoute
  '/seances': typeof SeancesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/exercices': typeof ExercicesRoute
  '/planning': typeof PlanningRoute
  '/progression': typeof ProgressionRoute
  '/reglages': typeof ReglagesRoute
  '/seances': typeof SeancesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bienvenue': typeof BienvenueRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/exercices': typeof ExercicesRoute
  '/planning': typeof PlanningRoute
  '/progression': typeof ProgressionRoute
  '/reglages': typeof ReglagesRoute
  '/seances': typeof SeancesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenue'
    | '/confidentialite'
    | '/exercices'
    | '/planning'
    | '/progression'
    | '/reglages'
    | '/seances'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenue'
    | '/confidentialite'
    | '/exercices'
    | '/planning'
    | '/progression'
    | '/reglages'
    | '/seances'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/bienvenue'
    | '/confidentialite'
    | '/exercices'
    | '/planning'
    | '/progression'
    | '/reglages'
    | '/seances'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BienvenueRoute: typeof BienvenueRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ExercicesRoute: typeof ExercicesRoute
  PlanningRoute: typeof PlanningRoute
  ProgressionRoute: typeof ProgressionRoute
  ReglagesRoute: typeof ReglagesRoute
  SeancesRoute: typeof SeancesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue': {
      id: '/bienvenue'
      path: '/bienvenue'
      fullPath: '/bienvenue'
      preLoaderRoute: typeof BienvenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercices': {
      id: '/exercices'
      path: '/exercices'
      fullPath: '/exercices'
      preLoaderRoute: typeof ExercicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progression': {
      id: '/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof ProgressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seances': {
      id: '/seances'
      path: '/seances'
      fullPath: '/seances'
      preLoaderRoute: typeof SeancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BienvenueRoute: BienvenueRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ExercicesRoute: ExercicesRoute,
  PlanningRoute: PlanningRoute,
  ProgressionRoute: ProgressionRoute,
  ReglagesRoute: ReglagesRoute,
  SeancesRoute: SeancesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
